---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-on-k8s
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
configMapGenerator:
  - name: config
    literals:
      - app.message=Hello Kubernetes!
